/* Oma's Mahjong — all texts of the game, in Dutch and English side by side: key: [nl, en].
   A text with numbers or names is a function. tx('key', ...) gives the text in the player's language
   (S.lang, chosen in the settings; Dutch unless English is picked). The family dashboard stays Dutch. */
'use strict';

const LANGS = { nl: 'Nederlands', en: 'English' };
const langOf = st => st.lang || (typeof START_ENGLISH !== 'undefined' && START_ENGLISH.includes(st.pid) ? 'en' : 'nl');
const isEn = () => typeof S !== 'undefined' && langOf(S) === 'en';
const pl = (n, one, more) => n === 1 ? one : more;
const TEXT = {
  // ---------- general ----------
  gotIt: ['Begrepen!', 'Got it!'],
  close: ['Sluiten', 'Close'],
  menu: ['Menu', 'Menu'],
  nice: ['Fijn! 😊', 'Lovely! 😊'],
  hooray: ['Hoera!', 'Hooray!'],
  levelN: [n => `Level ${n}`, n => `Level ${n}`],
  levelsN: [n => `${n} ${pl(n, 'level', 'levels')}`, n => `${n} ${pl(n, 'level', 'levels')}`],
  days: [n => `${n} ${pl(n, 'dag', 'dagen')}`, n => `${n} ${pl(n, 'day', 'days')}`],
  daysInRow: [n => `${n} ${pl(n, 'dag', 'dagen')} op rij`, n => `${n} ${pl(n, 'day', 'days')} in a row`],
  points: [n => `${n} punten`, n => `${n} points`],
  hoursMin: [(h, m) => h ? `${h} u ${m} min` : `${m} min`, (h, m) => h ? `${h} h ${m} min` : `${m} min`],
  months: [['januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december'],
    ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']],
  weekdays: [['ma', 'di', 'wo', 'do', 'vr', 'za', 'zo'], ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']],
  newVersion: ['✨ Nieuwe versie! Even geduld…', '✨ New version! One moment…'],
  updatedTo: [v => `✨ Bijgewerkt naar versie ${v}`, v => `✨ Updated to version ${v}`],
  version: [v => `Versie ${v}`, v => `Version ${v}`],

  // ---------- home and menu screens (index.html: data-t) ----------
  play: ['Spelen', 'Play'],
  daily: ['Dagpuzzel', 'Daily puzzle'],
  levels: ['Levels', 'Levels'],
  themes: ["Thema's", 'Themes'],
  prizes: ['Prijzen', 'Trophies'],
  ranking: ['Ranglijst', 'Leaderboard'],
  settings: ['Instellingen', 'Settings'],
  hint: ['Hint', 'Hint'],
  shuffle: ['Schudden', 'Shuffle'],
  restartLevel: ['Level opnieuw beginnen', 'Restart level'],
  playDaily: ['Speel', 'Play'],
  thisWeek: ['📅 Deze week', '📅 This week'],
  allTime: ['🏆 Altijd', '🏆 All time'],
  trophyCabinet: ['Prijzenkast', 'Trophy cabinet'],
  tilesHead: ['Stenen', 'Tiles'],
  bgHead: ['Achtergrond', 'Background'],
  greet: [h => h < 6 ? 'Goedenacht, oma! 🌙' : h < 12 ? 'Goedemorgen, oma! ☀️' : h < 18 ? 'Goedemiddag, oma! 🌼' : 'Goedenavond, oma! 🌙',
    h => h < 6 ? 'Good night! 🌙' : h < 12 ? 'Good morning! ☀️' : h < 18 ? 'Good afternoon! 🌼' : 'Good evening! 🌙'],
  continueLevel: [n => `Verder met level ${n}`, n => `Continue level ${n}`],
  dailyDone: ['Vandaag gehaald! 👑', 'Done today! 👑'],
  dailyWaiting: ['Nieuwe puzzel wacht!', 'A new puzzle is waiting!'],
  goalSun: [n => `Nog <b>${pl(n, '1 level', n + ' levels')}</b> tot de hoofdprijs: het <b>Zonnebloem-thema</b>!`, n => `<b>${pl(n, '1 more level', n + ' more levels')}</b> to the big prize: the <b>Sunflower theme</b>!`],
  goalAllBgs: ['Alle achtergronden vrijgespeeld! 🏆', 'All backgrounds unlocked! 🏆'],
  goalBg: [(n, name) => `Nog <b>${n} ⭐</b> tot achtergrond “${name}”`, (n, name) => `<b>${n} ⭐</b> more to the “${name}” background`],
  record: [s => `Record: ${s}`, s => `Best: ${s}`],
  calCount: [(a, b) => `Deze maand: ${a} van ${b} 👑`, (a, b) => `This month: ${a} of ${b} 👑`],
  puzzleToday: ['Puzzel van vandaag', "Today's puzzle"],
  puzzleOf: [(d, m) => `Puzzel van ${d} ${m}`, (d, m) => `Puzzle of ${m} ${d}`],
  playAgain: [' · nog eens', ' · again'],
  dailyTitle: [(d, m) => `Dagpuzzel ${d} ${m}`, (d, m) => `Daily ${m} ${d}`],
  sunName: ['Zonnebloem', 'Sunflower'],
  inUse: ['In gebruik ✨', 'In use ✨'],
  tapToUse: ['Tik om te gebruiken', 'Tap to use'],
  sunLocked: [n => `De hoofdprijs! Speel level ${n} uit`, n => `The big prize! Finish level ${n}`],
  sunAbout: ['Zonnige stenen, zomermuziek met vogeltjes en bloemen-effecten', 'Sunny tiles, summer music with birds and flower effects'],
  sunProgress: [(a, b) => `${a} van de ${b} levels uitgespeeld`, (a, b) => `${a} of ${b} levels finished`],
  sunNeedMore: [n => `Speel nog ${n} levels uit om de Zonnebloem te winnen 🌻`, n => `Finish ${n} more levels to win the Sunflower theme 🌻`],
  bgSunLocked: [n => `Dit veld hoort bij de Zonnebloem-prijs: speel level ${n} uit 🌻`, n => `This field comes with the Sunflower prize: finish level ${n} 🌻`],
  bgNeedStars: [(n, name) => `Verdien nog ${n} ⭐ om “${name}” vrij te spelen`, (n, name) => `Earn ${n} more ⭐ to unlock “${name}”`],
  won: ['Gewonnen ✓', 'Won ✓'],
  theme_classic: ['Klassiek', 'Classic'], theme_fruit: ['Lekkernijen', 'Treats'], theme_animals: ['Dieren', 'Animals'], theme_sunflower: ['Zonnebloem', 'Sunflower'], theme_happy: ['Vrolijk', 'Cheerful'],
  bg_jade: ['Jade', 'Jade'], bg_sunrise: ['Zonsopgang', 'Sunrise'], bg_lavender: ['Lavendel', 'Lavender'], bg_ocean: ['Oceaan', 'Ocean'], bg_blossom: ['Bloesem', 'Blossom'],
  bg_forest: ['Bos', 'Forest'], bg_night: ['Sterrennacht', 'Starry night'], bg_gold: ['Goud', 'Gold'], bg_rainbow: ['Regenboog', 'Rainbow'], bg_sunfield: ['Zonnebloemveld', 'Sunflower field'],

  // ---------- settings ----------
  set_sfx: ['🔊 Geluidjes', '🔊 Sounds'],
  set_music: ['🎵 Muziek', '🎵 Music'],
  set_vibrate: ['📳 Trillen', '📳 Vibration'],
  set_highlight: ['✨ Vastzittende stenen donker', '✨ Darken tiles that are stuck'],
  set_nums: ['🔢 Cijfers in de hoek', '🔢 Numbers in the corner'],
  set_bigTiles: ['🔍 Extra grote stenen', '🔍 Extra large tiles'],
  set_contrast: ['🌓 Extra duidelijk (hoog contrast)', '🌓 Extra clear (high contrast)'],
  set_lang: ['🌐 Taal', '🌐 Language'],
  howToPlay: ['Hoe speel je?', 'How to play'],
  wipe: ['🗑️ Voortgang wissen', '🗑️ Erase progress'],
  bigOn: ['Vanaf het volgende level: minder en grotere stenen 🔍', 'From the next level: fewer, larger tiles 🔍'],
  bigOff: ['Vanaf het volgende level weer gewone stenen', 'From the next level: normal tiles again'],
  wipeTitle: ['Voortgang wissen?', 'Erase progress?'],
  wipeText: ['Alle levels, sterren, dagpuzzels, prijzen en het Zonnebloem-thema worden gewist. Je begint weer bij <b>level 1</b>.', 'All levels, stars, daily puzzles, trophies and the Sunflower theme will be erased. You start again at <b>level 1</b>.'],
  wipeWarn: ['Dit kan niet ongedaan worden gemaakt.', 'This cannot be undone.'],
  wipeNo: ['Nee, bewaren', 'No, keep it'],
  wipeYes: ['Ja, alles wissen', 'Yes, erase everything'],
  wiped: ['Je voortgang is gewist. Veel plezier vanaf level 1!', 'Your progress has been erased. Have fun from level 1!'],

  // ---------- how to play (checked against the rules in board.js) ----------
  introTitle: ['Zo speel je 🀄', 'How to play 🀄'],
  intro1: ['Tik op een <b>vrije steen</b>: hij schuift naar een van de <b>4 vakjes bovenaan</b>.', 'Tap a <b>free tile</b>: it moves into one of the <b>4 slots at the top</b>.'],
  intro2: ['Komen er <b>twee dezelfde</b> in de vakjes, dan verdwijnen ze! Er zijn maar <b>4 vakjes</b>: komt er een 4e steen zonder paar bij, dan is het level voorbij.', 'When <b>two of the same</b> tiles meet in the slots, they disappear! There are only <b>4 slots</b>: if a 4th tile without a partner is added, the level is over.'],
  intro3: [n => `Vrij = niets erbovenop, en links óf rechts open. Vanaf level ${n} mag je per level één keer <b>💡 Hint</b> en één keer <b>🔀 Schudden</b>.`, n => `Free = nothing on top of it, and its left <i>or</i> right side open. From level ${n} you may use <b>💡 Hint</b> once and <b>🔀 Shuffle</b> once in every level.`],
  introLang: ['🇬🇧 English?', '🇳🇱 Nederlands?'],
  downTitle: ['Omgedraaide stenen', 'Face-down tiles'],
  down1: ['Sommige stenen liggen <b>omgedraaid</b>. Tik er één keer op om te kijken wat het is, en nog een keer om hem te pakken.', 'Some tiles lie <b>face down</b>. Tap one once to see what it is, and once more to take it.'],
  down2: ['Er kan maar <b>één steen tegelijk</b> open liggen. Een open steen telt alsof hij al gepakt is: draai je daarna <b>dezelfde</b> om, of tik je er een aan, dan verdwijnen ze meteen. Staat de tweeling al in een vakje? Dan verdwijnen ze ook meteen bij het omdraaien. Is het een andere, dan gaat de vorige weer dicht. Goed onthouden dus! 🧠',
    'Only <b>one tile at a time</b> can lie turned over. A turned-over tile counts as already picked: if you then turn over <b>the same picture</b>, or tap a matching tile, both disappear at once. Is its twin already in a slot? Then they disappear as soon as you turn it over. If it is a different picture, the previous one turns back. So remember it well! 🧠'],

  // ---------- playing ----------
  againPraise: ['Nog een keer! 💪', 'Once more! 💪'],
  dailyPraise: ['📅 Dagpuzzel', '📅 Daily puzzle'],
  stillStuck: ['Die zit nog vast: kies een steen met een open zijkant', 'That one is still stuck: pick a tile with an open side'],
  trayFull: ['Alle vakjes zijn vol. Kies een steen die past!', 'All slots are full. Pick a tile that matches!'],
  praiseList: [['Mooi!', 'Goed zo!', 'Prima!', 'Geweldig!', 'Fantastisch!', 'Super!', 'Knap hoor!', 'Prachtig!'], ['Nice!', 'Well done!', 'Great!', 'Brilliant!', 'Fantastic!', 'Super!', 'Clever!', 'Beautiful!']],
  superCombo: ['Supercombo! 🌈', 'Super combo! 🌈'],
  combo: [n => `Combo x${n} 🔥`, n => `Combo x${n} 🔥`],
  lastPair: ['Laatste paar! 🎉', 'Last pair! 🎉'],
  almostDone: ['Bijna klaar!', 'Almost done!'],
  miles: [['', 'Al een kwart! 🌟', 'Halverwege! 💪', 'Nog maar een kwart! 🚀'], ['', 'A quarter done! 🌟', 'Halfway! 💪', 'Only a quarter left! 🚀']],
  fullTitle: ['Oei, alle vakjes zijn vol!', 'Oops, all the slots are full!'],
  fullText: ['Alle 4 vakjes zitten vol zonder paar. Geen nood, probeer het gewoon nog eens!', 'All 4 slots are full without a pair. No worries, just try again!'],
  tryAgain: ['↻ Opnieuw proberen', '↻ Try again'],
  toolsLocked: [n => `Hint en Schudden komen vrij vanaf level ${n} 🔒`, n => `Hint and Shuffle unlock at level ${n} 🔒`],
  hintUsed: ['Je hint voor dit level is al gebruikt', 'You already used your hint in this level'],
  shuffleUsed: ['Je hebt in dit level al geschud', 'You already shuffled in this level'],
  noWay: ['Zo gaat het niet meer lukken… probeer 🔀 Schudden', "This won't work out any more… try 🔀 Shuffle"],
  restartTitle: ['Opnieuw beginnen?', 'Start again?'],
  restartText: ['Het level begint dan weer vanaf het begin, met dezelfde stenen. Je krijgt je hint en schudden terug.', 'The level starts again from the beginning, with the same tiles. You get your hint and shuffle back.'],
  restartYes: ['↻ Ja, opnieuw', '↻ Yes, start again'],
  restartNo: ['Nee, verder spelen', 'No, keep playing'],
  // grandma's extra help
  rescueText: ['Geen nood! Je mag de stenen <b>één keer</b> terugleggen en gewoon verder spelen.', 'No worries! You may put the tiles back <b>once</b> and simply play on.'],
  rescueBack: ['↩ Stenen terugleggen', '↩ Put the tiles back'],
  rescueCost: ['Dit kost één ⭐', 'This costs one ⭐'],
  startAgain: ['Opnieuw beginnen', 'Start again'],
  tilesBack: ['De stenen liggen weer op het bord 💪', 'The tiles are back on the board 💪'],
  keepShuffle: ['Bewaar schudden voor als je vastzit 😉', 'Save the shuffle for when you are stuck 😉'],
  // special tiles
  goldPair: ['✨ Gouden paar! x2', '✨ Golden pair! x2'],
  twoJokers: ['🃏 Twee jokers!', '🃏 Two jokers!'],
  goldNew: ['✨ Nieuw: een gouden paar geeft dubbele punten!', '✨ New: a golden pair gives double points!'],
  joker: ['🃏 Joker!', '🃏 Joker!'],
  jokerFinale: [n => `🃏 Joker-finale! +${n}`, n => `🃏 Joker finale! +${n}`],
  locksOpen: ['🔓 Sloten open!', '🔓 Locks open!'],
  iceMelted: ['🧊 Ijs gesmolten!', '🧊 Ice melted!'],
  iceCrack: ['🧊 Krak! Nog één keer', '🧊 Crack! One more time'],
  iceThick: ['🧊 Dik ijs: haal 2 stenen ernaast weg', '🧊 Thick ice: remove 2 tiles around it'],
  iceThin: ['🧊 Bevroren: haal eerst een steen ernaast weg', '🧊 Frozen: first remove a tile around it'],
  lockedTap: ['🔒 Op slot: speel eerst het 🔑-paar weg', '🔒 Locked: first clear the 🔑 pair'],
  iceSun: ['☀️ Het ijs smelt vanzelf', '☀️ The ice melts by itself'],
  newTile: [t => `Nieuw: ${t}`, t => `New: ${t}`],
  nt_joker2: ['De joker', 'The joker'],
  nt_joker2_text: ['De joker past bij <b>elke</b> steen! Zitten er stenen in je vakjes? Tik de joker aan: hij haalt er een weg, <b>samen met zijn tweeling</b>, waar die ook ligt. Zijn je vakjes leeg? Dan wacht de joker en neemt hij de volgende steen mee.',
    'The joker fits <b>every</b> tile! Are there tiles in your slots? Tap the joker: it takes one of them away, <b>together with its twin</b>, wherever that lies. Are your slots empty? Then the joker waits and takes the next tile you tap along with it.'],
  nt_ice: ['Bevroren stenen', 'Frozen tiles'],
  nt_ice_text: ['Sommige stenen zitten vast in het <b>ijs</b>. Haal een steen weg die ernaast, erop of eronder ligt: dan smelt het ijs. Bij dik ijs ❄️❄️ moet dat twee keer.',
    'Some tiles are stuck in the <b>ice</b>. Remove a tile next to it, on top of it or underneath it, and the ice melts. Thick ice ❄️❄️ needs that twice.'],
  nt_lock: ['Slot en sleutel', 'Lock and key'],
  nt_lock_text: ['Stenen met een <b>slotje</b> kun je pas pakken als je het paar met de <b>🔑 sleutel</b> hebt weggespeeld. Zoek dus eerst de sleutels!',
    'Tiles with a <b>lock</b> can only be taken once you have cleared the pair with the <b>🔑 key</b>. So look for the keys first!'],

  // ---------- rewards ----------
  myStats: ['📊 Mijn prestaties', '📊 My achievements'],
  st_levels: ['Levels uitgespeeld', 'Levels finished'], st_stars: ['Sterren', 'Stars'], st_pairs: ['Paren gemaakt', 'Pairs made'],
  st_points: ['Punten', 'Points'], st_daily: ['Dagpuzzels', 'Daily puzzles'], st_streak: ['Langste reeks', 'Longest streak'],
  st_combo: ['Beste combo', 'Best combo'], st_time: ['Speeltijd', 'Time played'], st_chests: ['Schatkisten', 'Treasure chests'],
  st_hearts: ['Hartjes gekregen', 'Hearts received'], st_lucky: ['Geluksmomenten', 'Lucky moments'], st_weeks: ['Weken gewonnen', 'Weeks won'],
  task_pairs: [g => `Maak ${g} paren`, g => `Make ${g} pairs`],
  task_levels: [g => `Speel ${g} levels uit`, g => `Finish ${g} levels`],
  task_daily: ['Speel de dagpuzzel', 'Play the daily puzzle'],
  task_combo: [g => `Maak ${g} paren vlak na elkaar`, g => `Make ${g} pairs in quick succession`],
  task_stars3: ['Haal 3 sterren in een level', 'Get 3 stars in a level'],
  task_flips: [g => `Draai ${g} stenen om`, g => `Turn over ${g} tiles`],
  task_points: [g => `Verdien ${g} punten`, g => `Earn ${g} points`],
  task_nohelp: ['Speel een level uit zonder hint of schudden', 'Finish a level without hint or shuffle'],
  taskDone: [s => `✅ Taak klaar: ${s} (+1 ⭐)`, s => `✅ Task done: ${s} (+1 ⭐)`],
  allTasksDone: ['🎁 Alle taken klaar! Open je schatkist in het menu', '🎁 All tasks done! Open your treasure chest in the menu'],
  tasksTitle: ['📋 Taken van vandaag', "📋 Today's tasks"],
  taskDoneShort: ['Klaar! +1 ⭐', 'Done! +1 ⭐'],
  chestOpened: ['Schatkist van vandaag is open. Morgen nieuwe taken!', "Today's treasure chest is open. New tasks tomorrow!"],
  chestReady: ['Tik om je schatkist te openen!', 'Tap to open your treasure chest!'],
  chestNeed: [n => `Maak alle 3 taken af voor de schatkist (${n}/3)`, n => `Finish all 3 tasks for the treasure chest (${n}/3)`],
  tasksFirst: ['Eerst alle 3 taken afmaken 😊', 'Finish all 3 tasks first 😊'],
  chestTitle: ['Schatkist!', 'Treasure chest!'],
  ptsWord: ['punten', 'points'],
  starsWord: ['sterren', 'stars'],
  newTasksTomorrow: ['Morgen staan er weer nieuwe taken klaar.', 'Tomorrow there will be new tasks.'],
  lucky: ['🍀 Geluksmoment! Pak snel de glinsterende steen', '🍀 Lucky moment! Quickly take the sparkling tile'],
  luckyGot: [n => `🍀 Geluk! +${n}`, n => `🍀 Lucky! +${n}`],
  giftTitle: ['Je dagcadeau!', 'Your daily gift!'],
  giftText: [name => `Fijn dat je er weer bent${name ? ', ' + name : ''}! Tik op het cadeau.`, name => `Lovely to see you again${name ? ', ' + name : ''}! Tap the present.`],
  giftOpen: ['Openmaken! 🎉', 'Open it! 🎉'],
  giftStars: [n => `+${n} ${pl(n, 'ster', 'sterren')}! 🎉`, n => `+${n} ${pl(n, 'star', 'stars')}! 🎉`],
  giftEnjoy: ['Veel speelplezier vandaag! 😊', 'Enjoy playing today! 😊'],

  // ---------- winning ----------
  winTitles: [['Prachtig gedaan!', 'Geweldig, oma!', 'Wat knap!', 'Fantastisch!', 'Heel goed gedaan!'], ['Beautifully done!', 'Brilliant!', 'How clever!', 'Fantastic!', 'Very well done!']],
  dailyWon: ['Dagpuzzel gehaald! 👑', 'Daily puzzle done! 👑'],
  noRescueStars: ['Zonder terugleggen verdien je ⭐⭐⭐', 'Without putting tiles back you earn ⭐⭐⭐'],
  noHelpStars: ['Zonder hint en schudden verdien je ⭐⭐⭐', 'Without hint and shuffle you earn ⭐⭐⭐'],
  toCalendar: ['Naar de kalender', 'To the calendar'],
  nextLevel: [n => `Volgende: level ${n} ▶`, n => `Next: level ${n} ▶`],
  scoreWord: ['Punten', 'Points'],
  timeWord: ['Tijd', 'Time'],
  inARow: [n => `${n} op rij`, n => `${n} in a row`],
  perfect: ['PERFECT! ✨', 'PERFECT! ✨'],
  chase: [(r, p, who) => `📅 Weekstrijd plek #${r} · nog <b>${p}</b> punten tot ${who}`, (r, p, who) => `📅 Weekly challenge place #${r} · <b>${p}</b> points to ${who}`],
  famWeek: ['👪 Familie deze week', '👪 Family this week'],
  family: ['👪 Familie', '👪 Family'],
  toolsNew: ['Nieuw vrijgespeeld! 🎉', 'Newly unlocked! 🎉'],
  toolsText: ['Vanaf nu heb je in elk level <b>één Hint</b> en <b>één keer Schudden</b>.', 'From now on you have <b>one Hint</b> and <b>one Shuffle</b> in every level.'],
  toolsNote: ['💡 Hint wijst een slimme zet aan. 🔀 Schudden husselt de stenen, handig als je vastzit. Zonder ze te gebruiken verdien je ⭐⭐⭐.', '💡 Hint shows a smart move. 🔀 Shuffle mixes up the tiles, handy when you are stuck. Win without using them to earn ⭐⭐⭐.'],
  top: ['Top!', 'Great!'],
  sunWin: ['De hoofdprijs is van jou!', 'The big prize is yours!'],
  sunWinText: ['Je hebt het <b>Zonnebloem-thema</b> gewonnen: zonnige stenen, een zomers zonnebloemveld, vrolijke muziek met vogeltjes en bloemen die opspringen bij elk paar!', 'You have won the <b>Sunflower theme</b>: sunny tiles, a summery sunflower field, cheerful music with birds and flowers that pop up with every pair!'],
  sunUse: ['🌻 Gebruik het nu', '🌻 Use it now'],
  sunLater: ["Later (staat bij Thema's)", 'Later (you find it under Themes)'],
  newTrophies: [n => `${pl(n, 'Nieuwe prijs!', 'Nieuwe prijzen!')} 🏅`, n => `${pl(n, 'New trophy!', 'New trophies!')} 🏅`],
  seeCabinet: ['Bekijk de prijzenkast', 'See the trophy cabinet'],
  newBg: ['Nieuwe achtergrond! 🎉', 'New background! 🎉'],
  newBgText: [name => `Je hebt <b>“${name}”</b> vrijgespeeld.`, name => `You have unlocked <b>“${name}”</b>.`],
  newBgWhere: ["Je kunt hem kiezen bij <b>🎨 Thema's</b> in het menu.", 'You can pick it under <b>🎨 Themes</b> in the menu.'],
  fun: ['Leuk!', 'Nice!'],

  // ---------- trophies ----------
  tr_l1: ['Eerste level', 'First level'], tr_l1_d: ['Speel level 1 uit', 'Finish level 1'],
  tr_l5: ['Op weg', 'On your way'], tr_l5_d: ['Speel 5 levels uit', 'Finish 5 levels'],
  tr_l10: ['Doorzetter', 'Keeping at it'], tr_l10_d: ['Speel 10 levels uit', 'Finish 10 levels'],
  tr_l20: ['Zonnebloem', 'Sunflower'], tr_l20_d: [n => `Speel ${n} levels uit`, n => `Finish ${n} levels`],
  tr_l30: ['Kampioen', 'Champion'], tr_l30_d: ['Speel 30 levels uit', 'Finish 30 levels'],
  tr_l50: ['Mahjong-koningin', 'Mahjong queen'], tr_l50_d: ['Speel 50 levels uit', 'Finish 50 levels'],
  tr_p5: ['Perfect', 'Perfect'], tr_p5_d: ['5 levels met 3 sterren', '5 levels with 3 stars'],
  tr_p20: ['Sterrenregen', 'Shower of stars'], tr_p20_d: ['20 levels met 3 sterren', '20 levels with 3 stars'],
  tr_s50: ['Sterrenverzamelaar', 'Star collector'], tr_s50_d: ['Verdien 50 sterren', 'Earn 50 stars'],
  tr_d1: ['Dagpuzzelaar', 'Daily puzzler'], tr_d1_d: ['Speel je eerste dagpuzzel', 'Play your first daily puzzle'],
  tr_d10: ['Trouwe puzzelaar', 'Faithful puzzler'], tr_d10_d: ['Speel 10 dagpuzzels', 'Play 10 daily puzzles'],
  tr_r3: ['Op dreef', 'On a roll'], tr_r3_d: ['3 dagen op rij gepuzzeld', 'Puzzled 3 days in a row'],
  tr_r7: ['Hele week!', 'A whole week!'], tr_r7_d: ['7 dagen op rij gepuzzeld', 'Puzzled 7 days in a row'],
  tr_m100: ['100 paren', '100 pairs'], tr_m100_d: ['Maak 100 paren', 'Make 100 pairs'],
  tr_m500: ['500 paren', '500 pairs'], tr_m500_d: ['Maak 500 paren', 'Make 500 pairs'],
  tr_c5: ['Supercombo', 'Super combo'], tr_c5_d: ['Maak 5 paren vlak na elkaar', 'Make 5 pairs in quick succession'],
  tr_k5: ['Schatzoeker', 'Treasure hunter'], tr_k5_d: ['Open 5 schatkisten', 'Open 5 treasure chests'],
  tr_h3: ['Geliefd', 'Loved'], tr_h3_d: ['Krijg 3 hartjes van familie', 'Get 3 hearts from family'],
  tr_w1: ['Weekwinnaar', 'Week winner'], tr_w1_d: ['Word 1e in de weekstrijd', 'Come 1st in the weekly challenge'],

  // ---------- ranking and profile ----------
  you: ['Jij', 'You'],
  youTag: ['(jij)', '(you)'],
  levelWord: [n => `level ${n}`, n => `level ${n}`],
  botTitle: ['computerspeler', 'computer player'],
  weekLeft: [(d, h) => d >= 1 ? `nog ${d} ${pl(d, 'dag', 'dagen')}${h ? ` en ${h} uur` : ''}` : `nog ${Math.max(1, h)} uur`, (d, h) => d >= 1 ? `in ${d} ${pl(d, 'day', 'days')}${h ? ` and ${h} ${pl(h, 'hour', 'hours')}` : ''}` : `in ${Math.max(1, h)} ${pl(Math.max(1, h), 'hour', 'hours')}`],
  weekInfo: [s => `⏳ De weekstrijd eindigt ${s}. Elke maandag begint iedereen weer bij 0!`, s => `⏳ The weekly challenge ends ${s}. Every Monday everyone starts again at 0!`],
  allInfo: ['Wie is het verst gekomen? Het hoogste level staat bovenaan.', 'Who got furthest? The highest level is at the top.'],
  rankNoteOnline: ['🌐 Familie online · 💛 = stuur een hartje · 🤖 = computerspeler', '🌐 Family online · 💛 = send a heart · 🤖 = computer player'],
  rankNoteBots: ['🤖 = computerspeler', '🤖 = computer player'],
  pickName: ['Naam kiezen', 'Choose a name'],
  profile: ['Mijn profiel', 'My profile'],
  whatName: ['Hoe heet je?', "What's your name?"],
  nameWhy: ['Zo zien de anderen je op de ranglijst.', 'This is how the others see you on the leaderboard.'],
  namePh: ['Bijvoorbeeld: Oma Riet', 'For example: Grandma Rose'],
  quickNames: [['Oma', 'Opa', 'Mama', 'Papa'], ['Grandma', 'Grandpa', 'Mum', 'Dad']],
  frameTitle: ['Lijstje om je plaatje', 'Frame around your picture'],
  save: ['Opslaan', 'Save'],
  frameHow: [h => `Dit lijstje krijg je met: ${h}`, h => `You get this frame with: ${h}`],
  nameFirst: ['Vul eerst een naam in', 'Fill in a name first'],
  fr_none: ['Geen', 'None'], fr_bronze: ['Brons', 'Bronze'], fr_silver: ['Zilver', 'Silver'], fr_gold: ['Goud', 'Gold'], fr_sun: ['Zonnebloem', 'Sunflower'],
  fr_heart: ['Hartjes', 'Hearts'], fr_rainbow: ['Regenboog', 'Rainbow'], fr_crown: ['Kroon', 'Crown'],
  how_prizes: [n => `${n} prijzen`, n => `${n} trophies`], how_level: [n => `level ${n}`, n => `level ${n}`],
  how_hearts: ['3 hartjes krijgen', 'get 3 hearts'], how_combo: ['Supercombo', 'Super combo'], how_week: ['win een week', 'win a week'],
  lastWeekTitle: [r => `Vorige week werd je #${r}!`, r => `Last week you came #${r}!`],
  lastWeekText: [(p, r) => `Je haalde <b>${p} punten</b> in de weekstrijd.${r === 1 ? ' Je bent de <b>weekwinnaar</b>! 👑' : r <= 3 ? ' Wat een mooie plek!' : ''}`, (p, r) => `You scored <b>${p} points</b> in the weekly challenge.${r === 1 ? ' You are the <b>week winner</b>! 👑' : r <= 3 ? ' What a great place!' : ''}`],
  newWeekNote: ['Er is een nieuwe week begonnen: iedereen staat weer op 0. Zet hem op!', 'A new week has started: everyone is back at 0. Go for it!'],
  newWeek: ['Nieuwe week!', 'New week!'],
  climbWeek: ['Je klimt in de weekstrijd! 📅', 'You climb in the weekly challenge! 📅'],
  climbAll: ['Je klimt op de ranglijst! 🏆', 'You climb the leaderboard! 🏆'],
  next: ['Verder', 'Continue'],
  passedOne: [n => `Je bent <b>${n}</b> voorbij! 🎉`, n => `You passed <b>${n}</b>! 🎉`],
  passedMany: [n => `Je bent <b>${n} spelers</b> voorbij! 🎉`, n => `You passed <b>${n} players</b>! 🎉`],
  gapTo: [(gap, who) => `Nog ${gap} tot ${who}`, (gap, who) => `${gap} to ${who}`],
  onTop: ['Je staat bovenaan! 👑', 'You are at the top! 👑'],
  weekEnds: [s => `⏳ De week eindigt ${s}`, s => `⏳ The week ends ${s}`],

  // ---------- hearts ----------
  sendHeartLbl: ['Stuur een hartje', 'Send a heart'],
  heartAlready: [n => `Je hebt ${n} vandaag al een hartje gestuurd 💛`, n => `You already sent ${n} a heart today 💛`],
  heartAlreadyShort: ['Vandaag al een hartje gestuurd 💛', 'Already sent a heart today 💛'],
  heartFor: [n => `Hartje voor ${n}`, n => `A heart for ${n}`],
  heartMsgQ: ['Wil je er een berichtje bij doen?', 'Would you like to add a message?'],
  heartOnly: ['Alleen een hartje 💛', 'Just a heart 💛'],
  heartFail: ['Hartje versturen lukte niet. Is er internet?', 'Sending the heart did not work. Is there internet?'],
  heartSent: ['Hartje verstuurd!', 'Heart sent!'],
  heartSentText: [n => `<b>${n}</b> krijgt je hartje te zien zodra ze de app opent.`, n => `<b>${n}</b> will see your heart as soon as they open the app.`],
  heartSentNote: ['Op de ranglijst zie je daarna "gezien 👀" staan.', 'On the leaderboard you will then see "seen 👀".'],
  heartSeenTag: ['💛 hartje gezien 👀', '💛 heart seen 👀'],
  heartOnWay: ['💛 hartje onderweg…', '💛 heart on its way…'],
  heartSeenToast: [n => `💛 ${n || 'Ze'} heeft je hartje gezien!`, n => `💛 ${n || 'They'} saw your heart!`],
  someone: ['Iemand', 'Someone'],
  heartForYou: ['Een hartje voor jou!', 'A heart for you!'],
  heartFrom1: [n => `<b>${n}</b> stuurde je een hartje!`, n => `<b>${n}</b> sent you a heart!`],
  heartFromMany: [(a, b) => `<b>${a}</b> en <b>${b}</b> stuurden je een hartje!`, (a, b) => `<b>${a}</b> and <b>${b}</b> sent you a heart!`],
  howSweet: ['Wat lief! 😊', 'How sweet! 😊'],
  and: ['en', 'and'],
  sendsYou: [n => n > 1 ? 'sturen je een hartje!' : 'stuurt je een hartje!', n => n > 1 ? 'send you a heart!' : 'sends you a heart!'],
  tapToPlay: ['Tik om verder te spelen', 'Tap to keep playing'],
  quickMsgs: [lv => ['Goed bezig! 💪', 'Ik denk aan je 😘', 'Dank je wel! 😊', `Ik ben bij level ${lv}! 🧩`], lv => ['Well done! 💪', 'Thinking of you 😘', 'Thank you! 😊', `I'm at level ${lv}! 🧩`]],

  // ---------- iPhone ----------
  iosTitle: ['Zet het spel op je beginscherm', 'Put the game on your home screen'],
  iosSteps: ['1. Tik onderaan op <b>Deel</b> <span style="font-size:24px">⬆️</span> (het vierkantje met de pijl).<br>2. Kies <b>Zet op beginscherm</b> ➕.<br>3. Tik op <b>Voeg toe</b>.', '1. Tap <b>Share</b> <span style="font-size:24px">⬆️</span> at the bottom (the square with the arrow).<br>2. Choose <b>Add to Home Screen</b> ➕.<br>3. Tap <b>Add</b>.'],
  iosNote: ["Dan staat Oma's Mahjong als app tussen je andere apps, zonder Safari eromheen.", "Then Oma's Mahjong sits among your other apps, without Safari around it."],
};
// the text for key in the player's language (a function is called with the extra arguments)
function tx(key, ...a) {
  const v = TEXT[key];
  if (!v) return key;
  const s = v[isEn() ? 1 : 0];
  return typeof s === 'function' ? s(...a) : s;
}
const locale = () => isEn() ? 'en-GB' : 'nl-NL';
// the fixed texts in index.html (data-t="key", data-t-label for aria-labels)
function applyLang() {
  document.documentElement.lang = isEn() ? 'en' : 'nl';
  document.querySelectorAll('[data-t]').forEach(el => { el.textContent = tx(el.dataset.t); });
  document.querySelectorAll('[data-t-label]').forEach(el => el.setAttribute('aria-label', tx(el.dataset.tLabel)));
  const wd = tx('weekdays'); document.querySelectorAll('.cal-days span').forEach((el, i) => el.textContent = wd[i]);
}
